/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cachedb.server;

import com.cachedb.core.*;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        CacheDB cacheDB = new CacheDB();
        CommandProcessor processor = new CommandProcessor(cacheDB);

        try (Scanner scanner = new Scanner(System.in)) {
            while (true) {
                String command = scanner.nextLine().trim();
                if (command.equalsIgnoreCase("EXIT")) {
                    System.out.println("Adios!");
                    break;
                }
                String result = processor.processCommand(command);
                System.out.println(result);
            }
        } finally {
            cacheDB.shutdown();
        }
    }
}